## 작업형 제1유형 : 데이터 처리 영역

### 예시문제
    mtcars 데이터셋(mtcars.csv)의 qsec 컬럼을 최소최대 척도(Min-Max Scale)로 변환한 후 0.5보다 큰 값을 가지는 레코드 수를 구하시오

In [14]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv('../data/DA/01/mtcars.csv')

In [16]:
data.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [8]:
print(data.shape)

(32, 12)


In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
 11  carb        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [17]:
from sklearn.preprocessing import MinMaxScaler 

In [18]:
min_max_scaler = MinMaxScaler()

In [21]:
qsec = data['qsec'].to_numpy()
qsec

array([16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.  , 22.9 ,
       18.3 , 18.9 , 17.4 , 17.6 , 18.  , 17.98, 17.82, 17.42, 19.47,
       18.52, 19.9 , 20.01, 16.87, 17.3 , 15.41, 17.05, 18.9 , 16.7 ,
       16.9 , 14.5 , 15.5 , 14.6 , 18.6 ])

In [30]:
# 아래와 같은 모양으로 array 만들어야함..
qsec = qsec.reshape(-1,1)
qsec

array([[16.46],
       [17.02],
       [18.61],
       [19.44],
       [17.02],
       [20.22],
       [15.84],
       [20.  ],
       [22.9 ],
       [18.3 ],
       [18.9 ],
       [17.4 ],
       [17.6 ],
       [18.  ],
       [17.98],
       [17.82],
       [17.42],
       [19.47],
       [18.52],
       [19.9 ],
       [20.01],
       [16.87],
       [17.3 ],
       [15.41],
       [17.05],
       [18.9 ],
       [16.7 ],
       [16.9 ],
       [14.5 ],
       [15.5 ],
       [14.6 ],
       [18.6 ]])

In [31]:
qsec_scale = min_max_scaler.fit_transform(qsec)
qsec_scale

array([[0.23333333],
       [0.3       ],
       [0.48928571],
       [0.58809524],
       [0.3       ],
       [0.68095238],
       [0.15952381],
       [0.6547619 ],
       [1.        ],
       [0.45238095],
       [0.52380952],
       [0.3452381 ],
       [0.36904762],
       [0.41666667],
       [0.41428571],
       [0.3952381 ],
       [0.34761905],
       [0.59166667],
       [0.47857143],
       [0.64285714],
       [0.65595238],
       [0.28214286],
       [0.33333333],
       [0.10833333],
       [0.30357143],
       [0.52380952],
       [0.26190476],
       [0.28571429],
       [0.        ],
       [0.11904762],
       [0.01190476],
       [0.48809524]])

In [33]:
result = len(qsec_scale[qsec_scale> 0.5])
print(result)

9
